spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rhinitis-local?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: amiless951
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
## basic log level for all messages
#logging.level.org.hibernate=info
## SQL statements and parameters
#logging.level.org.hibernate.SQL=debug
#logging.level.org.hibernate.orm.jdbc.bind=trace
## Statistics and slow queries
#logging.level.org.hibernate.stat=debug
#logging.level.org.hibernate.SQL_SLOW=info
## 2nd Level Cache
#logging.level.org.hibernate.cache=debug
logging:
  level:
    org:
      hibernate:
        sql: debug
        orm:
          jdbc:
            bind: trace